### ISSUE TITLE
Possible to share postgrex connection with Ecto?

### ISSUE THREAD

**Issue by keichan34** [opendrops/phoenix-pubsub-postgres#3]
I wonder how possible this is? 

This is more of a nice-to-have feature. There are some merits (and demerits) of having the PubSub connection separate from the data connection; it'd be nice to let the user choose.

**Comment by narrowtux** [comment]
It's not possible because the Postgrex notification module makes its own connection to the database. It should be quite easy to write your configuration in a way that it is used by both Ecto and this pubsub adapter.
